name: autorrl
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image